### ISSUE TITLE
Is there a way to turn off the dead torrent filter option?

### ISSUE THREAD

**Issue by Tenome** [ArjixGamer/Nyaa-Utility#16]
I don't want it enabled because torrent stats often aren't reliable (dead torrents sometimes still have a seeder, etc.).

Edit: Opening the extension's XPI and blanking the ,js did the trick. Having it as an option that you can toggle would be useful though.

**Comment by ArjixWasTaken** [comment]
Funny that you asked 😁

This extension has gone through two rewrites, and that is actually an implemented feature.
The only issue is that I kinda never finished the 2nd rewrite, so that update was never delivered.

---

It was implemented in the first rewrite, [source](https://github.com/ArjixWasTaken/Nyaa-Utility/blob/rewrite/src/Modules/deadTorrentRemover.tsx), but not in the 2nd one.

**Comment by ArjixWasTaken** [comment]
I'm thinking of re-writing this extension for a third time, so if you have any suggestions, please put them here or make separate issues.

Why am I not satisfied with the previous rewrite?
Well, my knowledge in programming constantly changes, so I never really like my old code.

**Comment by Tenome** [comment]
Having a visible number on the extension icon itself to indicate the amount of new notifications would be useful, rather than having to manually check the Notifications tab.

**Comment by ArjixWasTaken** [comment]
Suggestions will be managed [here](https://github.com/ArjixWasTaken/Nyaa-Utility/issues/17), so I am closing this issue
